.TH FRELAY-GUI "1" "September 2016" "frelay-gui 0.0.1" "User Commands"
.SH NAME
frelay-gui \- relayed file transfer client GUI front-end
.SH SYNOPSIS
.B frelay-gui
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
Frelay is a simple software to transfer individual files between clients
connected to an intermediate relay server. It consists of a server
component, an interactive command line client, and an optional GUI client
front-end.
.TP
\fBFrelayclt-gui\fR is the client GUI front-end.
.SH OPTIONS
.TP
\fB\-c\fR  \fI\,FILE\/\fR
read configuration from specified file
.SH "REPORTING BUGS"
Report bugs on: https://github.com/irrwahn/frelay/issues
.br
Frelay home page: https://github.com/irrwahn/frelay
.SH COPYRIGHT
Copyright \(co 2016 Urban Wallasch
.br
